- easyaudit/middleware/easyaudit.py
middleware init with optional kwarg.
I was getting a startup error because the `__init__` apparently wants no arguments. The mixin class's `__init__` had it as a default variable, so I did the same (I could have just not subclassed the init of course).
> middleware init with optional kwarg.

- easyaudit/models.py
- easyaudit/signals.py
This PR updates django-easy-audit to log m2m-changed signals. I'm still fixing the following two issues:
1) Each M2M update is recorded twice, because M2M changes send two signals (`pre_add`/`post_add` for additions and `pre_remove`/`post_remove` for deletions).
* I am going to filter out half of the signals. I would prefer to keep the pre-save actions (`pre_add` and `pre_remove`), but to be consistent with easyaudit's other signals, I am going to keep the post-save ones (`post_add` and `post_remove`).
2) Reverse M2M updates do not include the M2M change in the audit log.
* Reverse M2M updates (e.g. if the `Business` model has a ManyToManyField connected to `User`, a reverse add would be `some_user.business_set.add(some_business)`, as opposed to `some_business.users.add(some_user)`) do …
> Log `m2m_changed` signal

- easyaudit/signals.py
This PR addresses the follow-up items from #20. @soynatan, let me know if you have questions or concerns. Thanks! 
Most of the new code is for logging related objects' keys after reverse M2M changes. Prior to these changes, these fields were not serialized in `CRUDEvent.object_json_repr` because they are not stored in a concrete model field.
The changes add three new fields to `object_json_repr` for reverse M2M information:
* `m2m_rev_action` - the M2M action, i.e. `post_add`, `post_remove`, or `post_clear`
* `m2m_rev_model` - the name of the related model whose instances have been added or removed
* `m2m_rev_pks` - the primary keys of all related model instances connected to this object after the action was performed
The new `m2m_rev_*` fields will be ignored by Django's deserializer …
> Log reverse M2M changes

- easyaudit/signals.py
Hi @soynatan! Thanks for your work on this library. We were on the hunt for a django auditing lib, and yours was just the thing!
After integrating, we noticed when running our tests that there were more audit queries than we expected. A little digging led us to find two `save()` calls in `signals.py` that look redundant with the `create()` calls above them. I'm a bit new to django development, so I checked the relevant docs to be sure:
https://docs.djangoproject.com/en/1.11/ref/models/querysets/#create
This PR just removes the redundant `save()` calls, which should be a nice performance boost for those (like us!) using the library heavily in their apps. 
I ran the tests after making this change, and also did some live tests in our app (not referenced in this PR, naturally), and things …
> Removed redundant save() calls (create() includes implicit save())

- easyaudit/migrations/0001_initial.py
- easyaudit/models.py
`on_delete` on ForeignKeys is required since Django 2.0, see https://docs.djangoproject.com/en/1.11/ref/models/fields/#foreignkey
> Make it run with Django 2.0

- easyaudit/signals/request_signals.py
Simple fix for when the session is not used for authentication
I ran into this on my project, because we don't usually use the HTTP session.
It may be worth researching ways to plug in other authentication systems, but that is out of this scope.
> on session get, .get() on user id.

- easyaudit/signals/request_signals.py
Unfortunately, I ran into issues during my project's unit tests. This seems to work. Please check on your end, too.
> Bugfix: check if HTTP_COOKIE is truthy, and use django's version.

- easyaudit/settings.py
- easyaudit/signals/auth_signals.py
- easyaudit/signals/request_signals.py
This change allows users to configure what header is used for looking up the remote IP of the request. This is useful when a server behind a load balancer needs the IP of the request, and not the IP of the load balancer.
> Make remote IP header configurable for servers behind load balancers

- easyaudit/settings.py
- easyaudit/signals/request_signals.py
I noticed that it was possible to specify a list of models to audit, ignoring all the others. This wasn't possible with url requests so I tried to implement it.
Setting the variable DJANGO_EASY_AUDIT_REGISTERED_URLS as a list of url patterns will allow to choose what url request to audit and ignore all the others.
> Implemented auditing of ONLY REGISTERED_URLS

- easyaudit/models.py
- easyaudit/signals/model_signals.py
- easyaudit/tests/test_app/tests.py
Hello! Great project, thanks a lot!
I updated the code to not create CRUDEvent if none of the fields has changed.
> Do not create CRUDEvent on update if none of the fields has changed.

- README.md
- easyaudit/backends.py
- easyaudit/settings.py
- easyaudit/signals/auth_signals.py
- easyaudit/signals/model_signals.py
- easyaudit/signals/request_signals.py
This PR adds a setting to the library, making it more pluggable to end users.
We have encountered that the database table became too large for our operations, and decided to log our audit events to ElasticSearch instead. With the changes in this pr, it's possible to change the logging backend to whatever the end user prefers, instead of being forced to create a database table for audit logs.
A simple example for kibana is given in the readme.
> Add a pluggable logging backend

- easyaudit/admin.py
- easyaudit/admin_helpers.py
The list view in the admin panels is quite slow, especially for the CRUD events. The reason is that it has to do separate queries for the user (and the content type for CRUD events) for each row. This change ensures that all those related objects are fetched in the original query, which gives a pretty massive speed-up.
> Increase admin list panel performance by selecting related

- README.md
- easyaudit/admin.py
- easyaudit/admin_helpers.py
- easyaudit/settings.py
- easyaudit/tests/test_app/tests.py
Add the setting `DJANGO_EASY_AUDIT_READONLY_EVENTS` to make CRUD events read-only from the admin UI.
Setting to True will do the following:
- Disable purge
- Set CRUDEvent delete permission to false
- Set all fields of CRUDEvent to read-only
Note: _The details view of the CRUDEvent retains a "save" button, but no change can be made._
> Read only events admin

- .github/workflows/build.yml
- .travis.yml
- easyaudit/middleware/easyaudit.py
- easyaudit/signals/request_signals.py
- easyaudit/tests/test_app/tests.py
- easyaudit/tests/test_app/urls.py
- easyaudit/tests/test_app/views.py
- easyaudit/tests/test_project/asgi.py
- easyaudit/tests/test_project/settings.py
- setup.py
I have also created a test which utilizes ASGI (the view being called is synchronous, but that's fine!). Testing websocket at some point would be nice, as well as async views (websockets can be synchronous, which is a pattern django channels offers as a concrete solution). But yes, websockets likely would require django channels (not opposed to making it an extra install which is grabbed by the test runner), and that's outside the scope of this code change as that's not truly supported in django at this time (not natively).
> ASGI RequestEvent support

- .github/workflows/build.yml
- .travis.yml
code is fine, just we needed to explicitly install the correct django version (because we're not using requirements or any other binding mechanism).
> CI builds install explicit django version

- easyaudit/__init__.py
Addresses deprecation warning:
> RemovedInDjango41Warning: 'easyaudit' defines default_app_config = 'easyaudit.apps.EasyAuditConfig'.
Django now detects this configuration automatically. You can remove default_app_config.
See: https://docs.djangoproject.com/en/4.0/releases/3.2/#automatic-appconfig-discovery
> remove default_config for Django versions 3.2+

- easyaudit/admin_helpers.py
Fix for #190. EasyAuditModelAdmin.has_delete_permission() now respects user permissions if READONLY_EVENTS is False
> Fix EasyAuditModelAdmin.has_delete_permission()

- easyaudit/migrations/0013_auto_20190723_0126.py
Fixes #234 
The RunPython migration action was missing a reverse_code function.
This was set to RunPython.noop, as an index drop can't and shouldn't be reversed.
> Fix migration 0013 IrreversibleError

- easyaudit/crudhistory_admin_mixin.py
Issue: #192 
How to use:
1. Inherit your ModelAdmin class from `CRUDHistoryAdminMixin`
2. use filed `crud_history_link` in `list_display`, or in `fieldsets`
[Example in code](https://github.com/soynatan/django-easy-audit/pull/193/files#diff-26908206d45df23463eb5b22570c2d065e5f26ce9cd3d55b81a82be1b79bd0ddR100)
```
class SomeModelAdmin(CRUDHistoryAdminMixin):
list_display = (
"id",
"crud_history_link",
)
```
> Add helper to show CRUD history for particular object

- README.md
- easyaudit/signals/model_signals.py
If setting `DJANGO_EASY_AUDIT_CHECK_IF_REQUEST_USER_EXISTS` set to `False`, no `request.user` validation is made on DB.
This allow the calling project to ignore user validation and speed up audit creation, plus, save some DB queries.
> Allow to ignore request.user validation

- easyaudit/signals/model_signals.py
If we save a model with a db transaction and that model don't have audit active, it's making unnecessary db calls:
```
SAVEPOINT "xpto_x1";
RELEASE SAVEPOINT "xpto_x1";
```
This happens because django creates a save point if a transaction is open inside another transaction.
To avoid it, and save some db calls, do `should_audit(instance)` before creating `transaction.atomic`.
> Avoid DB savepoints if no audit is going to be created

- easyaudit/signals/request_signals.py
- easyaudit/tests/test_app/tests.py
The ASGI [HTTP Request context provides](https://asgi.readthedocs.io/en/latest/specs/www.html#http-connection-scope) a `client` value which should be reflected by the `remote_ip` value in the request info. Now the `server` value is reflected erroneously.
> ASGI scope `client` value should be converted to the remote_ip

- easyaudit/utils.py
`timezone.utc` is deprecated and therefore the following `RemovedInDjango50Warning` is emitted during our tests:
```shell
ERROR    easyaudit.signals.model_signals:model_signals.py:125 easy audit had a pre-save exception.
Traceback (most recent call last):
File "<snip>/.venv/lib/python3.10/site-packages/easyaudit/signals/model_signals.py", line 72, in pre_save
delta = model_delta(old_model, instance)
File "<snip>/.venv/lib/python3.10/site-packages/easyaudit/utils.py", line 57, in model_delta
new_value = get_field_value(new_model, field)
File "<snip>/.venv/lib/python3.10/site-packages/easyaudit/utils.py", line 28, in get_field_value
value = timezone.make_naive(value, timezone=timezone.utc)
File "<snip>/.venv/lib/python3.10/site-packages/django/utils/timezone.py", line 49, in __getattr__ …
```
> fix: replace timezone.utc with datetime.timezone.utc

- README.md
- easyaudit/settings.py
- easyaudit/signals/auth_signals.py
- easyaudit/signals/model_signals.py
- easyaudit/tests/test_app/tests.py
- easyaudit/utils.py
Hi @jheld ,
This is a PR for https://github.com/soynatan/django-easy-audit/issues/247 , let me know if there's something I need to change.
> Implemented `DJANGO_EASY_AUDIT_PROPAGATE_EXCEPTIONS` setting

- .github/workflows/build.yml
- setup.py
This PR is stacked on top of #264.
Add the release candidate 1 of Django 5.0 to the test matrix.
Also removed the upper version bound (see: https://iscinumpy.dev/post/bound-version-constraints/) to allow users to install this package with higher versions to test and changed the lower version bound to 3.2 (based on the test matrix).
> chore: add Django 5 to test matrix

- easyaudit/signals/model_signals.py
since recent versions, easyaudit raises exceptions when something goes wrong in the signal handlers, independent of whether it is configured to do so or not.
the crud_flow functions are not called immediately, but passed as callbacks to be called later on. thus, the checked propagation in the exception handlers below is bypassed.
> raise exceptions only when they should be propagated

- .github/workflows/build.yml
- easyaudit/__init__.py
- setup.py
Changes minimum supported version to Django 4.2 in preparation of LTS for Django 3.2 ending in April.
Fixes #269
> Drop support for Django 3.2

- pyproject.toml
Semantic versions must be in the form `MAJOR.MINOR.PATCH-PRERELEASE`. The currently applied semver violates the spec.
This is important for CD to function properly. An invalid semver string will cause the job to fail, as it did here: https://github.com/soynatan/django-easy-audit/actions/runs/8333068101/job/22803668383#step:7:9
> Fix semver

- easyaudit/signals/crud_flows.py
This typo tripped me up when debugging #307 since it was stating "pre_save exception" when it was happening in the post delete.
> Log correct signal names on CRUDEvent creation exception

- easyaudit/signals/crud_flows.py
- easyaudit/signals/model_signals.py
- tests/test_main.py
If the model changes are committed in a transaction, at the time when the post delete signal is handled instance.pk returns None.
This PR changes the logic such that the instance ID is retrieved before this happens, so that it is available when the event is logged and the CRUDEvent created.
Fixes #307
> Properly handle post delete in transactions

- easyaudit/middleware/easyaudit.py
- tests/test_main.py
Replaced standard threading with 'asgiref.local' in EasyAuditMiddleware. Also, made EasyAuditMiddleware extend Django's MiddlewareMixin to automatically handle sync and async execution modes. Github issue: #291
> Update `EasyAuditMiddleware` to support async context
