easyaudit/models.py, easyaudit/settings.py, easyaudit/signals.py
allow just appending unregistered classes
get the class for models if provided as strings.
crud event keep user id if deleted
store datetime with timezone info
=> allow appending unregistered classes , models if provided as strings. etc

easyaudit/settings.py, easyaudit/signals.py
allow crud difference callbacks; if any false do not create crud
use dispatch_uid on signal connections so they are guaranteed just one run per that module import
=> allow crud difference callbacks to determine of CRUDEvent should be created

easyaudit/signals.py
try to use the User's USERNAME_FIELD when getting the "username"
=> try to use the User's USERNAME_FIELD when getting the "username"

easyaudit/signals.py
enables logging for post-save and delete exceptions
=> enables logging for post-save and delete exceptions

easyaudit/middleware/easyaudit.py, easyaudit/signals.py
=> Uses local threading to make request and user available globally

easyaudit/models.py
=> Adds composite index for `object_id` & `context_type` on `CRUDEvent`.

easyaudit/models.py, easyaudit/signals.py
Adds support for m2m-changed signals to django-easy-audit. Details in #20 and #21.
=> M2m changed

MANIFEST.in, easyaudit/admin.py, easyaudit/admin_helpers.py, easyaudit/settings.py, easyaudit/signals/request_signals.py, easyaudit/templates/admin/easyaudit/change_list.html, easyaudit/templates/admin/easyaudit/purge_confirmation.html
Just standard Django admin staff added for easier search and navigation of collected audit data,
plus "purge" action added to let superuser remove all rows from EasyAudit tables
=> Improved admin: Added filters and hyperlinks to admin; "Purge" action added to let superuser remove all rows from EasyAudit tables.

easyaudit/admin.py, easyaudit/admin_helpers.py, easyaudit/tests/test_app/tests.py
=> Updated import for reverse to support Django 2.0

README.md
... and corrected indentation as a bonus
=> let there be colour

easyaudit/signals/model_signals.py
Return from signal if a fixture is loading. 
https://docs.djangoproject.com/en/2.0/ref/signals/#pre-save
https://docs.djangoproject.com/en/2.0/ref/signals/#post-save
Check raw param.
=> Added code to check for loading fixtures

setup.py
Version number changed to 1.1 for new release with latest bugfixes (https://github.com/soynatan/django-easy-audit/pull/58 and https://github.com/soynatan/django-easy-audit/pull/61)
=> Changed version to 1.1

easyaudit/admin.py, easyaudit/settings.py
=> Add configuration settings for admin search fields

easyaudit/signals/model_signals.py
just an extra try/except if we hit an issue trying to log an error on CRUDEvent.
=> Bugfix: CRUDEvent signal error log try/except

easyaudit/migrations/0013_auto_20190723_0126.py
Reverts soynatan/django-easy-audit#139
=> Revert "Fix #105"

easyaudit/admin.py, easyaudit/admin_helpers.py
@jdkizer9 thank you for the implementation!
fixes issue #95
=> escaped some text

README.md
=> Add pypi bagde

easyaudit/admin.py
Added ability to export easyaudit events to CSV
=> Export audit events to CSV

.github/workflows/build.yml, setup.py
This results in the need to remove python versions less than 3.8 otherwise it won't install.
Let me know if you want me to bump the version in `setup.py`
=> Add support for Django 4.2.

easyaudit/signals/auth_signals.py
=> Make REMOTE_ADDR optional

.github/workflows/ci.yml
Add supported Django versions to CI matrix again.
=> ci: add django versions to CI matrix
